### PR TITLE
Bug 1069458 - Typo in Kit Builder

### PR DESCRIPTION
**Pull request by ReemHA**
The typo in the word "Preperation" is corrected to "Preparation". A bug in index.html.

### CODE REVIEW

**Comment by ScottDowne** [comment]
Looks like there are some variable names and other uses of the incorrect spelling:

https://github.com/mozilla/webmaker-kits-builder/search?utf8=%E2%9C%93&q=preperation&type=Code

**Comment by ReemHA** [comment]
Yes I noticed, I only changed the one between the html tags. Should I
change the variable names?

**Comment by ScottDowne** [comment]
Yeah, should probably update all uses of it while we are here.

**Comment by ReemHA** [comment]
I already did now. Hope I didn't miss something this time.

**Comment by ReemHA** [comment]
I wonder why its not fixed on the main website
http://kitbuilder.webmakerprototypes.org/ though the code is valid

**Comment by ScottDowne** [comment]
I have landed the code, but it has not yet been pushed live.

**Comment by ReemHA** [comment]
So should I change the status to resolved or wait till its pushed live? and
thanks again for the help

**Pull request merged**
